# Generated by Django 3.2.4 on 2021-06-10 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.CharField(max_length=250)),
                ('equipo', models.CharField(max_length=250)),
                ('CRM', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalle', models.TextField()),
                ('solicitante', models.CharField(max_length=250)),
                ('area', models.CharField(choices=[('infra', 'Infraestructura'), ('SS', 'Subsuelo')], default='infra', max_length=100)),
                ('sector', models.CharField(choices=[('mante', 'Mantenimiento'), ('bunker', 'Bunker')], default='mante', max_length=100)),
                ('observaciones', models.TextField()),
                ('responsable_seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
